version: '3'
services:
  api:
    image: 'csz3qe/multi-server'
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - PGDATABASE=$PGDATABASE
      - PGHOST=$PGHOST
      - PGPORT=$PGPORT
  worker:
    image: 'csz3qe/multi-worker'
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  client:
    image: 'csz3qe/multi-client'
    mem_limit: 128m
  nginx:
    image: 'csz3qe/multi-nginx'
    mem_limit: 128m
    ports:
      - '80:80'
    restart: always