name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Dev Image
        run: docker build -t client_test -f ./client/Dockerfile.dev ./client
        
      - name: Test Dev Image
        run: docker run client_test npm run test
  
      - name: Build Client Prod Image
        run: docker build -t csz3qe/multi-client ./client
      
      - name: Build Nginx Prod Image
        run: docker build -t csz3qe/multi-nginx ./nginx
        
      - name: Build Server Prod Image
        run: docker build -t csz3qe/multi-server ./server
        
      - name: Build Worker Prod Image
        run: docker build -t csz3qe/multi-worker ./worker
        
  publish:
    
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Publish client image
        run: docker push csz3qe/multi-client
      
      - name: Publish nginx image
        run: docker push csz3qe/multi-nginx
        
      - name: Publish server image
        run: docker push csz3qe/multi-server
        
      - name: Publish worker image
        run: docker push csz3qe/multi-worker
