name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Dev Image
        run: docker build -t client_test -f ./client/Dockerfile.dev ./client
        
      - name: Test Dev Image
        run: docker run client_test npm run test
  
      - name: Build Client Prod Image
        run: docker build -t csz3qe/multi-client ./client
      
      - name: Build Nginx Prod Image
        run: docker build -t csz3qe/multi-nginx ./nginx
      
      - name: Build Server Prod Image
        run: docker build -t csz3qe/multi-server ./server

      - name: Build Worker Prod Image
        run: docker build -t csz3qe/multi-worker ./worker
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Publish client image
        run: docker push csz3qe/multi-client
        
      - name: Publish nginx image
        run: docker push csz3qe/multi-nginx
        
      - name: Publish server image
        run: docker push csz3qe/multi-server
        
      - name: Publish worker image
        run: docker push csz3qe/multi-worker
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Zip deployable content
        run: zip deploy.zip docker-compose.yml
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          version_label: 12-8
          region: ap-south-1
          deployment_package: deploy.zip
  